name: adoptelecloud
favicon: null
layout_spectrum: 0.75405
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#819792'
    - '#444a4b'
    - '#3b231c'
  brandStrength: 0.75
  lightness: 0.5144006970804185
  saturation: 0.45934730605222285
  rhythmicContrast: 0.9574725907295942
purpose: []
